### ISSUE TITLE
Doom hotkeys for SPC f

### ISSUE THREAD

**Issue by user9856749** [ZacJoffe/zemacs#2]
I like your take on the doom SPC - hotkeys!
Does there exist an overview of the current doom hotkeys? I'd like to implement the SPC f functions. Sadly, I can't find a good overview of the current doom hotkeys. 
The ones I recall, and used are:
SPC f f -> Find file
SPC f . -> dired in local project root
SPC f P -> dired in private config folder
SPC f r -> list recent files. 

If you can provide me some resources, I can gladly implement some of these "missing" features. 

Thanks, for the great config.
Bob

**Comment by user9856749** [comment]
I found an overview of the doom emacs hotkeys. 
https://gist.github.com/hjertnes/9e14416e8962ff5f03c6b9871945b165#file-doom-txt

**Comment by ZacJoffe** [comment]
Hey, thanks for opening this issue. You can find the implementation of Doom's `SPC f` key bindings [here](https://github.com/doomemacs/doomemacs/blob/e96624926d724aff98e862221422cd7124a99c19/modules/config/default/+evil-bindings.el#L425-L444).

This config is not necessarily meant for general use; it's something that I built for myself and maintain for my specific usage. As I don't use these key bindings, I won't be implementing them in this config. You are more than welcome to take my general key bindings and add any of Doom's key bindings. Doing so should be trivial - you can follow [this pattern in the `general` config](https://github.com/ZacJoffe/zemacs/blob/5a9b24715025e7db6c25519b3eca1422a7226176/init.el#L1454-L1463).
